[DEFAULT]
mazetype = open
trainmethod = DRND
envtype = PointMaze
envid = PointMaze_Open-v3
renderenv = False
maxstepperepisode = 500
numenv = 4
numstep = 256
gamma = 0.999
intgamma = 0.995
lambda = 0.95
numtarget = 10
alpha = 0.9
drndlossweight = 1.0
extcoef = 1.0
intcoef = 1.0
learningrate = 3e-4
drndlearningrate = 1e-4
clipgradnorm = 0.5
epoch = 4
minibatch = 8
ppoeps = 0.1
entropycoef = 0.01
valuecoef = 0.5
updateproportion = 0.5
usegae = True
usegpu = True
usenoisynet = False
obsnormstep = 50
seed = 42
continuingtask = False
resettarget = False
usedensereward = False

[OPTIONS]
envtype = [atari, mario, ant_maze, point_maze]
mazetype = [umaze, open, medium, large]
trainmethod = DRND
envid = PointMaze_Open-v3
renderenv = False
maxstepperepisode = 500
numenv = 4
numstep = 256
gamma = 0.999
intgamma = 0.995
lambda = 0.95
numtarget = 10
alpha = 0.9
drndlossweight = 1.0
extcoef = 1.0
intcoef = 1.0
learningrate = 3e-4
drndlearningrate = 1e-4
clipgradnorm = 0.5
epoch = 4
minibatch = 8
ppoeps = 0.1
entropycoef = 0.01
valuecoef = 0.5
updateproportion = 0.5
usegae = True
usegpu = True
usenoisynet = False
obsnormstep = 50
seed = 42
continuingtask = False
resettarget = False
usedensereward = False

